name: Mirror for abgox

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: mirror-abgox

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJSON(vars.WHITE_REPO_LIST) }}
    steps:
      - uses: abgox/git-mirror-action@main
        with:
          src_url: git@github.com:abgox/${{ matrix.repo }}.git
          dst_url: git@gitee.com:abgox/${{ matrix.repo }}.git
          src_ssh_key: ${{ secrets.SSH_PRIVATE_KEY_GITHUB }}
          dst_ssh_key: ${{ secrets.SSH_PRIVATE_KEY_GITEE }}
          branches: all

      - uses: abgox/git-mirror-action@main
        with:
          src_url: git@github.com:abgox/${{ matrix.repo }}.git
          dst_url: git@atomgit.com:abgox/${{ matrix.repo }}.git
          src_ssh_key: ${{ secrets.SSH_PRIVATE_KEY_GITHUB }}
          dst_ssh_key: ${{ secrets.SSH_PRIVATE_KEY_ATOMGIT }}
          branches: all

  last_update:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Update
        shell: pwsh
        run: |
          (Get-Date).ToUniversalTime().AddHours(8).ToString("yyyy-MM-dd") | Out-File -FilePath last_update.txt -Encoding utf8

      - name: Commit and push changes
        shell: pwsh
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -u
          git commit -m "chore: automatically update some content"
          git push
