name: Mirror for ScoopInstaller

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "50 */4 * * *"

concurrency:
  group: mirror-scoop-installer

jobs:
  sync-gitee:
    name: Sync to Gitee
    runs-on: ubuntu-latest
    steps:
      - uses: abgox/hub-mirror-action@abgox
        with:
          src: github/ScoopInstaller
          dst: gitee/scoop-installer-mirrors
          dst_key: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: org
          force_update: true
          static_list: ${{ vars.WHITE_SCOOP_REPO_LIST}}
